language: node_js

cache:
  directories:
  - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: "12"
    - node_js: "14"
    - node_js: "16"

install: npm run setup

script:
- npm run test