name: Tests

on:
  push:
    branches: [master, v2]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [12.x, 14.x, 16.x]

    name: Tests (Node.js ${{ matrix.nodejs }})

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.nodejs }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs }}
          cache: 'npm'


      - name: Install dependencies
        run: npm run setup

      - name: Execute tests
        run: npm test